### ISSUE TITLE
Endpoints for networks

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-backend-py#10]
_From @georgiana-b on May 25, 2017 9:31_

As described in tenders-exposed/elvis-ember#167, we want to allow users to create and update networks even without having an account. 

If the user is authenticated:

- [ ] Create a network attached to the user account
- [ ] List the user's networks
- [ ] Update any network attached to the user account
- [ ] Delete any network attached to the user account

If the user is not authenticated:
 
- [ ] Create a network that is not attached to anyone
- [ ] Nobody would be allowed to update that network
- [ ] Nobody would be allowed to delete that network
- [ ] Create a background task to delete such networks after 7 days

Public endpoints:
-  [ ] View a network

So, if the user wants to update a network and/or to ensure its persistency she/he will have to create an account.

_Copied from original issue: tenders-exposed/elvis-backend#51_

**Comment by zufanka** [comment]
Looks good to me!

**Comment by georgiana-b** [comment]
This issue was moved to tenders-exposed/elvis-backend-node#7
